In [2]:
# NumPy & Pandas assignment
# Objective: hands-on practice with NumPy and Pandas to perform basic data analysis and manipulation.
# 
# This notebook implements the tasks from the provided screenshot and prints outputs for each step.

In [3]:
# Imports and setup
import numpy as np
import pandas as pd
np.random.seed(0)  # for reproducible random numbers


In [4]:
# Task 1: Create a NumPy array 1..50, reshape to 5x10 and print transpose
arr = np.arange(1,51)
mat = arr.reshape(5,10)
print("Original 5x10 matrix:\n", mat)
print("\nTranspose (10x5):\n", mat.T)


Original 5x10 matrix:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

Transpose (10x5):
 [[ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]
 [10 20 30 40 50]]


In [5]:
# Task 2: Generate 100 random integers between 1 and 1000 and compute mean, median, std
rand_ints = np.random.randint(1,1001,size=100)
print("Random integers (first 20 shown):", rand_ints[:20])
print(f"Mean: {rand_ints.mean():.2f}")
print(f"Median: {np.median(rand_ints):.2f}")
print(f"Std deviation: {rand_ints.std():.2f}")


Random integers (first 20 shown): [685 560 630 193 836 764 708 360  10 724 278 755 805 600  71 473 601 397
 315 706]
Mean: 524.97
Median: 551.50
Std deviation: 287.08


In [6]:
# Task 3: Create a Pandas Series from a list of fruits and display basic statistics
fruits = ['apple','banana','orange','apple','kiwi','banana','apple']
s = pd.Series(fruits)
print("Series:\n", s)
print("\nValue counts:\n", s.value_counts())
print("\nUnique fruits:", s.unique())


Series:
 0     apple
1    banana
2    orange
3     apple
4      kiwi
5    banana
6     apple
dtype: object

Value counts:
 apple     3
banana    2
orange    1
kiwi      1
Name: count, dtype: int64

Unique fruits: ['apple' 'banana' 'orange' 'kiwi']


In [7]:
# Task 4: Create a DataFrame with sample data and perform operations
data = {
    'Name': ['Alice','Bob','Charlie','Diana','Ethan'],
    'Age': [25, 30, 22, 35, 28],
    'Gender': ['F','M','M','F','M'],
    'Score': [88, 92, 67, 95, 73]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# a) Display top 3 rows
print("\nTop 3 rows:\n", df.head(3))
# b) Filter rows where Score > 80
print("\nRows with Score > 80:\n", df[df['Score']>80])
# c) Add a Grade column based on Score
def grade_from_score(s):
    if s>=90:
        return 'A'
    elif s>=80:
        return 'B'
    elif s>=70:
        return 'C'
    elif s>=60:
        return 'D'
    else:
        return 'F'
df['Grade'] = df['Score'].apply(grade_from_score)
print("\nDataFrame with Grade column:\n", df)


DataFrame:
       Name  Age Gender  Score
0    Alice   25      F     88
1      Bob   30      M     92
2  Charlie   22      M     67
3    Diana   35      F     95
4    Ethan   28      M     73

Top 3 rows:
       Name  Age Gender  Score
0    Alice   25      F     88
1      Bob   30      M     92
2  Charlie   22      M     67

Rows with Score > 80:
     Name  Age Gender  Score
0  Alice   25      F     88
1    Bob   30      M     92
3  Diana   35      F     95

DataFrame with Grade column:
       Name  Age Gender  Score Grade
0    Alice   25      F     88     B
1      Bob   30      M     92     A
2  Charlie   22      M     67     D
3    Diana   35      F     95     A
4    Ethan   28      M     73     C
